package com.fons.cloud.ai.trip.common.constants;

/**
 * 行程审核稳定问题编码，供审核规则、前端展示和整改说明共同引用。
 * 枚举名称就是对外编码，不使用自然语言消息参与业务判断。
 *
 * @author hongqy
 */
public enum ItineraryReviewIssueCode {

    TRAVEL_ORDER_ORIGIN_MISMATCH,
    TRAVEL_ORDER_DESTINATION_MISMATCH,
    TRAVEL_ORDER_DEPARTURE_DATE_MISMATCH,
    TRAVEL_ORDER_RETURN_DATE_MISMATCH,
    TRAVEL_ORDER_PENDING_APPROVAL,
    TRAVEL_ORDER_INACTIVE,

    TRAVEL_POLICY_MISSING,
    TRAVEL_POLICY_DESTINATION_MISMATCH,
    POLICY_EVIDENCE_MISSING,
    HOTEL_RATE_LIMIT_EXCEEDED,
    HOTEL_STAR_LIMIT_EXCEEDED,
    TRANSPORT_CABIN_LIMIT_EXCEEDED,
    APPROVAL_THRESHOLD_EXCEEDED,
    ADVANCE_BOOKING_DAYS_INSUFFICIENT,

    TRIP_DATE_RANGE_INVALID,
    PLANNING_CURRENCY_INVALID,
    PROPOSAL_COMPONENT_MISSING,
    TRANSPORT_TYPE_INVALID,
    TRANSPORT_ROUTE_MISMATCH,
    TRANSPORT_DEPARTURE_DATE_MISMATCH,
    TRANSPORT_TIME_INVALID,
    TRANSPORT_DURATION_MISMATCH,
    ROUND_TRIP_TIME_CONFLICT,
    HOTEL_CITY_MISMATCH,
    HOTEL_STAY_MISMATCH,
    PROPOSAL_METRICS_MISMATCH,
    PROPOSAL_SCORE_INVALID
}
